import Head from "next/head";
import { Poppins } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useQuote } from "../../utils";

const poppins = Poppins({ subsets: ["latin"], weight: ["200", "400"] });

export default function Home() {
  const [quote, changeQuote] = useQuote(false);
  const [cachedQuote, changeCachedQuote] = useQuote(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className} ${styles.container}`}>
        <div className={styles["card"]}>
          <div className={styles["quote-container"]}>
            {quote && <p className={styles["quote"]}>{quote}</p>}
            {!quote && <div className={styles["neumorphic-loader"]}></div>}
            <button
              className={styles["regenerate-button"]}
              onClick={() => changeQuote()}
            >
              Regenerate
            </button>
          </div>
        </div>
        <br></br>
        <div className={styles["card"]}>
          <div className={styles["quote-container"]}>
            {cachedQuote && <p className={styles["quote"]}>{cachedQuote}</p>}
            {!cachedQuote && (
              <div className={styles["neumorphic-loader"]}></div>
            )}
            <button
              className={styles["regenerate-button"]}
              onClick={() => changeCachedQuote()}
            >
              Regenerate Cached Quote
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
